version: '3.8'

services:

  django:
    container_name: onic-django
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8011
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: onic-postgres
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
