# Generated by Django 5.1.3 on 2025-11-13 18:13

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Categoría multimedia', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías Multimedia',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre y Apellidos', max_length=200)),
                ('email', models.CharField(help_text='Correo electrónico', max_length=200)),
                ('telefono', models.CharField(blank=True, default='', help_text='Teléfono de contacto', max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, default='', help_text='Ciudad de residencia', max_length=100, null=True)),
                ('pais', models.CharField(blank=True, default='', help_text='País de residencia', max_length=100, null=True)),
                ('textoMensage', models.TextField(help_text='Mensage', max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre colaborador', max_length=150)),
                ('cargo', models.CharField(help_text='Cargo', max_length=70)),
                ('perfil', ckeditor.fields.RichTextField(blank=True, default='', max_length=2000, verbose_name='Perfil')),
                ('fb', models.CharField(blank=True, default='', max_length=300, verbose_name='FaceBook')),
                ('tw', models.CharField(blank=True, default='', max_length=300, verbose_name='Twitter')),
                ('ln', models.CharField(blank=True, default='', max_length=300, verbose_name='Linkedin')),
                ('imagen', models.FileField(blank=True, upload_to='equipo/', verbose_name='Imagen 320 x 320px')),
                ('orden', models.CharField(help_text='Orden', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Equipo',
            },
        ),
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tema', models.CharField(help_text='Título del tema de mapas', max_length=200)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de publicación')),
                ('descripcion', models.CharField(help_text='Descripión', max_length=400)),
                ('imagen', models.FileField(default='', upload_to='imagenes/mapas', verbose_name='Imagen tema mapa Catalogo(450x370 px)')),
                ('imagen2', models.FileField(default='', upload_to='imagenes/mapas', verbose_name='Imagen tema mapa Grande')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mapas (Temas)',
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, default='', max_length=10000, verbose_name='Descripción')),
                ('vision', ckeditor.fields.RichTextField(blank=True, default='', max_length=10000, verbose_name='Visión')),
                ('justificacion', ckeditor.fields.RichTextField(blank=True, default='', max_length=10000, verbose_name='Justificación')),
                ('objetivos', ckeditor.fields.RichTextField(blank=True, default='', max_length=10000)),
                ('usuarios', ckeditor.fields.RichTextField(blank=True, default='', max_length=10000)),
                ('imagen', models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen 1020x 1042px')),
                ('imagen_vision', models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen-vision 470x610px')),
                ('imagen_jus', models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen-justificacion 500x382px')),
                ('imagen_obj', models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen-objetivos 500x30px')),
                ('imagen_users', models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen-usuarios 500x370')),
            ],
            options={
                'verbose_name_plural': 'Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('thumbnail_image', models.ImageField(upload_to='projects/', verbose_name='thumbnail image (750 x 520)')),
                ('thumbnail_image_small', models.ImageField(blank=True, null=True, upload_to='projects/small/', verbose_name='Small image')),
                ('iframe_url', models.URLField(verbose_name='Iframe URL')),
                ('iframe_css_top', models.IntegerField(blank=True, null=True, verbose_name='iframe css top')),
                ('payment_gateway_url', models.URLField(verbose_name='Payment Gateway URL')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='slug')),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='projects/pdf/', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Suscribir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(help_text='eMail', max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Suscribirse',
            },
        ),
        migrations.CreateModel(
            name='VideoSMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('url_video', models.TextField(max_length=250, verbose_name='ingrese la URL del vídeo.')),
            ],
            options={
                'verbose_name_plural': 'Video SMT',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Categoría', max_length=100)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='imagenes/categorias', verbose_name='Imagen categoria')),
                ('url', models.CharField(blank=True, help_text='URL', max_length=500, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('link_type', models.CharField(choices=[('normal', 'Normal'), ('blank', 'Open in a new tab')], default='normal', max_length=7, null=True)),
                ('intro_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Intro Content')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ('orden',),
                'unique_together': {('parent', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de publicación')),
                ('titulo', models.CharField(help_text='Título de la noticia', max_length=200)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
                ('imagen', models.FileField(upload_to='imagenes/', verbose_name='Imagen Destacado')),
                ('categoria_multimedia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria_multimedia')),
            ],
            options={
                'verbose_name_plural': 'Imagenes Multimedia',
            },
        ),
        migrations.CreateModel(
            name='MapasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de publicación')),
                ('titulo', models.CharField(help_text='Título de la noticia', max_length=200)),
                ('subtitulo', models.CharField(help_text='Sub título de la noticia', max_length=500)),
                ('imagen', models.FileField(upload_to='mapas/', verbose_name='Imagen mapa (770x450 px)')),
                ('imagen2', models.FileField(default='', upload_to='imagenes/mapas', verbose_name='Imagen tema mapa Grande')),
                ('fuente', models.CharField(blank=True, default='SMT', help_text='Fuente noticia', max_length=50, null=True)),
                ('html', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='pdf/', verbose_name='Archivo PDF')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('autor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mapa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.mapas')),
            ],
            options={
                'verbose_name_plural': 'Mapas Detalle',
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de publicación')),
                ('titulo', models.CharField(help_text='Título de la noticia', max_length=200)),
                ('subtitulo', models.CharField(help_text='Sub título de la noticia', max_length=500)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
                ('archivo_audio', models.FileField(blank=True, default='', null=True, upload_to='audio/', verbose_name='Archivo Audio')),
                ('orden', models.IntegerField(choices=[(0, 'Carrusel'), (1, 'Noticia 1'), (2, 'Novedades 2'), (3, 'Boletines 3'), (4, 'Mediateca 4'), (5, 'General')], default=0)),
                ('imagen', models.FileField(upload_to='imagenes/', verbose_name='Imagen Destacado')),
                ('fuente', models.CharField(blank=True, default='SMT', help_text='Fuente noticia', max_length=50, null=True)),
                ('html', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='pdf/', verbose_name='Archivo PDF')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('autor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField(blank=True, max_length=10000, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('noticia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.noticias')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('imagen', models.FileField(upload_to='imagenes/', verbose_name='Imagen Destacado')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de publicación')),
                ('titulo', models.CharField(help_text='Título de la noticia', max_length=200)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
                ('archivo_audio', models.FileField(blank=True, default='', null=True, upload_to='audio/podcast/', verbose_name='Archivo Audio')),
                ('categoria_multimedia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria_multimedia')),
            ],
            options={
                'verbose_name_plural': 'Podcast Multimedia',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Descripción de la sub categoría', max_length=100)),
                ('imagen', models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen categoria (1920x1042 px)')),
                ('url', models.CharField(help_text='Url ', max_length=100)),
                ('pestana_nueva', models.BooleanField(default=False)),
                ('orden', models.IntegerField(blank=True, default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.categoria')),
            ],
            options={
                'verbose_name_plural': 'Sub Categorías',
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='noticias',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generales.subcategoria'),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de publicación')),
                ('titulo', models.CharField(help_text='Título de la noticia', max_length=200)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
                ('html', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('categoria_multimedia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria_multimedia')),
            ],
            options={
                'verbose_name_plural': 'Videos Multimedia',
            },
        ),
    ]
