# Generated by Django 3.2.19 on 2023-09-12 13:49

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Categoría', max_length=100, unique=True)),
                ('imagen', models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre y Apellidos', max_length=200)),
                ('email', models.CharField(help_text='Correo electrónico', max_length=200)),
                ('telefono', models.CharField(blank=True, default='', help_text='Teléfono de contacto', max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, default='', help_text='Ciudad de residencia', max_length=100, null=True)),
                ('pais', models.CharField(blank=True, default='', help_text='País de residencia', max_length=100, null=True)),
                ('textoMensage', models.TextField(help_text='Mensage', max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('descripcion', ckeditor.fields.RichTextField(max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Suscribir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(help_text='eMail', max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Suscribirse',
            },
        ),
        migrations.CreateModel(
            name='VideoFaceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('url_video', models.TextField(max_length=250, verbose_name='ingrese la URL del vídeo.')),
            ],
            options={
                'verbose_name_plural': 'Videos FaceBookLive',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Descripción de la sub categoría', max_length=100)),
                ('imagen', models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen categoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.categoria')),
            ],
            options={
                'verbose_name_plural': 'Sub Categorías',
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Título de la noticia', max_length=200)),
                ('subtitulo', models.CharField(help_text='Sub título de la noticia', max_length=500)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True)),
                ('archivo_audio', models.FileField(blank=True, default='', null=True, upload_to='audio/', verbose_name='Archivo Audio')),
                ('ultima_hora', models.BooleanField()),
                ('fecha_inicio_publicacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de inicio de publicación')),
                ('fecha_final_publicacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de finalización de publicación')),
                ('orden_destacado', models.IntegerField(choices=[(0, 'Principal'), (1, 'Destacado 1'), (2, 'Destacado 2'), (3, 'Destacado 3'), (4, 'General 4')], default=0)),
                ('imagen_destacado', models.FileField(upload_to='imagenes/', verbose_name='Imagen Destacado')),
                ('fuente', models.CharField(default='INRAI', help_text='Fuente noticia', max_length=50)),
                ('html', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='pdf/', verbose_name='Archivo PDF')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('vistas', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcategoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.subcategoria')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField(blank=True, max_length=10000, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('noticia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.noticias')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
