# Generated by Django 5.1.3 on 2025-11-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='subcategoria',
        ),
    ]
