# Generated by Django 3.2.19 on 2023-09-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoFaceBook',
            new_name='VideoSMT',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='imagen_destacado',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='fecha_final_publicacion',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='fecha_inicio_publicacion',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='orden_destacado',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='ultima_hora',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='vistas',
        ),
        migrations.AddField(
            model_name='noticias',
            name='orden',
            field=models.IntegerField(choices=[(0, 'Carrusel'), (1, 'Noticia 1'), (2, 'Novedades 2'), (3, 'Boletines 3'), (4, 'Mediateca 4')], default=0),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fuente',
            field=models.CharField(blank=True, default='INRAI', help_text='Fuente noticia', max_length=50, null=True),
        ),
    ]
