# Generated by Django 5.1.3 on 2025-11-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_remove_noticias_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='donado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='meta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
