# Generated by Django 3.2.19 on 2023-09-26 08:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_auto_20230925_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='justificacion',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='nosotros',
            name='objetivos',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='nosotros',
            name='usuarios',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='nosotros',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=10000),
        ),
    ]
