# Generated by Django 3.2.19 on 2024-08-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_mapas_mapasdetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='pestana_nueva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='url',
            field=models.CharField(default=False, help_text='Url ', max_length=100),
            preserve_default=False,
        ),
    ]
