# Generated by Django 3.2.19 on 2023-09-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_auto_20230926_0824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
