# Generated by Django 3.2.19 on 2024-08-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0004_auto_20240819_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapas',
            name='imagen2',
            field=models.FileField(default='', upload_to='imagenes/mapas', verbose_name='Imagen tema mapa Grande'),
        ),
        migrations.AlterField(
            model_name='mapas',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/mapas', verbose_name='Imagen tema mapa Catalogo(450x370 px)'),
        ),
    ]
