# Generated by Django 3.2.19 on 2023-10-24 15:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0004_auto_20230926_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosmt',
            options={'verbose_name_plural': 'Video SMT'},
        ),
        migrations.AddField(
            model_name='nosotros',
            name='imagen',
            field=models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=10000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='justificacion',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=10000, verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=10000, verbose_name='Visión'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fuente',
            field=models.CharField(blank=True, default='SMT', help_text='Fuente noticia', max_length=50, null=True),
        ),
    ]
