# Generated by Django 3.2.19 on 2024-08-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0005_auto_20240819_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='orden',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
