# Generated by Django 3.2.19 on 2023-10-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0005_auto_20231024_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Categoría', max_length=100, unique=True)),
                ('imagen', models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Descripción de la sub categoría', max_length=100)),
                ('imagen', models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen categoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generales.categoria')),
            ],
            options={
                'verbose_name_plural': 'Sub Categorías',
                'unique_together': {('categoria', 'nombre')},
            },
        ),
    ]
