# Generated by Django 3.2.19 on 2023-10-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_categoria_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='subcategoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.subcategoria'),
        ),
    ]
