# Generated by Django 3.2.19 on 2024-08-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_subcategoria_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='categoria',
            name='pestana_nueva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='url',
            field=models.CharField(default=0, help_text='Url ', max_length=100),
            preserve_default=False,
        ),
    ]
