# Generated by Django 3.2.19 on 2024-02-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0007_auto_20231024_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='categoria',
        ),
    ]
