# Generated by Django 3.2.19 on 2024-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0007_auto_20240826_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapasdetalle',
            name='imagen2',
            field=models.FileField(default='', upload_to='imagenes/mapas', verbose_name='Imagen tema mapa Grande'),
        ),
    ]
