# Generated by Django 3.2.19 on 2024-09-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0008_mapasdetalle_imagen2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('orden',), 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='link_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('blank', 'Open in a new tab')], default='normal', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/categorias', verbose_name='Imagen categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Categoría', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='url',
            field=models.CharField(blank=True, help_text='URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generales.subcategoria'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('parent', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='pestana_nueva',
        ),
    ]
