# Generated by Django 3.2.19 on 2024-03-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0009_auto_20240307_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='imagen',
            field=models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen 1020x 1042px'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='imagen_jus',
            field=models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen-justificacion 500x382px'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='imagen_obj',
            field=models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen-objetivos 500x30px'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='imagen_users',
            field=models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen-usuarios 500x370'),
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='imagen_vision',
            field=models.FileField(blank=True, upload_to='imagenes/', verbose_name='Imagen-vision 470x610px'),
        ),
    ]
