# Generated by Django 3.2.19 on 2024-03-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0011_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='cargo',
            field=models.CharField(default=' ', help_text='Cargo', max_length=150),
            preserve_default=False,
        ),
    ]
