# Generated by Django 5.1.1 on 2024-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0011_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_video',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
