# Generated by Django 3.2.19 on 2024-03-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0012_equipo_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cargo',
            field=models.CharField(help_text='Cargo', max_length=70),
        ),
    ]
