# Generated by Django 5.1.1 on 2024-10-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0012_alter_project_url_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='iframe_css_top',
            field=models.IntegerField(blank=True, null=True, verbose_name='iframe css top'),
        ),
    ]
