# Generated by Django 3.2.19 on 2024-03-14 18:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0013_alter_equipo_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='perfil',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=2000, verbose_name='Perfil'),
        ),
    ]
