# Generated by Django 5.1.1 on 2024-10-11 00:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0013_project_iframe_css_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='intro_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Intro Content'),
        ),
    ]
