# Generated by Django 3.2.19 on 2024-03-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0014_equipo_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='orden',
            field=models.CharField(default=' ', help_text='Orden', max_length=4),
            preserve_default=False,
        ),
    ]
