# Generated by Django 5.1.1 on 2024-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0014_categoria_intro_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_image_small',
            field=models.ImageField(blank=True, null=True, upload_to='projects/small/', verbose_name='Small image'),
        ),
    ]
