# Generated by Django 5.1.1 on 2024-10-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0015_project_thumbnail_image_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='projects/pdf/', verbose_name='PDF'),
        ),
    ]
