# Generated by Django 3.2.19 on 2024-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0015_equipo_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='orden',
            field=models.IntegerField(choices=[(0, 'Carrusel'), (1, 'Noticia 1'), (2, 'Novedades 2'), (3, 'Boletines 3'), (4, 'Mediateca 4'), (5, 'General')], default=0),
        ),
    ]
