# Generated by Django 3.2.19 on 2024-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0018_imagenes_podcast_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Categoría multimedia', max_length=100, unique=True)),
                ('imagen', models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen categoria multimedia')),
            ],
            options={
                'verbose_name_plural': 'Categoría Multimedia',
            },
        ),
    ]
