# Generated by Django 3.2.19 on 2024-04-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0019_categoria_multimedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='categoria_multimedia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria_multimedia'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='categoria_multimedia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria_multimedia'),
        ),
        migrations.AddField(
            model_name='videos',
            name='categoria_multimedia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.categoria_multimedia'),
        ),
    ]
