# Generated by Django 3.2.19 on 2024-04-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0020_auto_20240404_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_multimedia',
            options={'verbose_name_plural': 'Categorías Multimedia'},
        ),
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name_plural': 'Imagenes Multimedia'},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name_plural': 'Podcast Multimedia'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos Multimedia'},
        ),
    ]
