# Generated by Django 3.2.19 on 2024-04-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0022_remove_categoria_multimedia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='imagen',
            field=models.FileField(default=1, upload_to='imagenes/', verbose_name='Imagen Destacado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='archivo_audio',
            field=models.FileField(blank=True, default='', null=True, upload_to='audio/podcast/', verbose_name='Archivo Audio'),
        ),
    ]
