# Generated by Django 3.2.19 on 2024-08-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0023_auto_20240405_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoria3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(default='', upload_to='fotos/', verbose_name='Archivo con Foto del Usuario')),
                ('imagen', models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen categoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generales.subcategoria')),
            ],
        ),
    ]
