# Generated by Django 3.2.19 on 2024-08-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0025_rename_user_subcategoria3_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria3',
            name='foto',
        ),
    ]
