# Generated by Django 3.2.19 on 2024-08-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0026_remove_subcategoria3_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria3',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen subcategoria'),
        ),
    ]
