# Generated by Django 3.2.19 on 2024-08-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0027_alter_subcategoria3_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoria3',
            options={'verbose_name_plural': 'Subcategorias +'},
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen categoria (450x370 px)'),
        ),
        migrations.AlterField(
            model_name='subcategoria3',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen subcategoria (770x450 px)'),
        ),
    ]
