# Generated by Django 3.2.19 on 2024-08-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0028_auto_20240808_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen mapa (770x450 px)')),
                ('subcategoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generales.noticias')),
            ],
            options={
                'verbose_name_plural': 'Mapas',
            },
        ),
        migrations.DeleteModel(
            name='SubCategoria3',
        ),
    ]
