# Generated by Django 3.2.19 on 2024-08-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0029_auto_20240808_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapas',
            old_name='subcategoria',
            new_name='noticia',
        ),
        migrations.AlterField(
            model_name='mapas',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/mapas', verbose_name='Imagen mapa (770x450 px)'),
        ),
    ]
