# Generated by Django 3.2.19 on 2024-08-08 21:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generales', '0030_auto_20240808_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapas',
            options={'verbose_name_plural': 'Categoria de Mapas'},
        ),
        migrations.RemoveField(
            model_name='mapas',
            name='noticia',
        ),
        migrations.AddField(
            model_name='mapas',
            name='titulo',
            field=models.CharField(default=1, help_text='Título de la noticia', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapas',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/mapas', verbose_name='Imagen mapa (450x370 px)'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/categorias', verbose_name='Imagen categoria (1920x1042 px)'),
        ),
        migrations.CreateModel(
            name='Mapas1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de publicación')),
                ('titulo', models.CharField(help_text='Título de la noticia', max_length=200)),
                ('subtitulo', models.CharField(help_text='Sub título de la noticia', max_length=500)),
                ('imagen', models.FileField(upload_to='mapas/', verbose_name='Imagen mapa (770x450 px)')),
                ('fuente', models.CharField(blank=True, default='SMT', help_text='Fuente noticia', max_length=50, null=True)),
                ('html', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='pdf/', verbose_name='Archivo PDF')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('autor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mapa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generales.mapas')),
            ],
            options={
                'verbose_name_plural': 'Detalle Mapas',
            },
        ),
    ]
