# Generated by Django 3.2.19 on 2024-08-10 15:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generales', '0031_auto_20240808_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mapas1',
            new_name='MapasDetalle',
        ),
        migrations.AlterModelOptions(
            name='mapas',
            options={'verbose_name_plural': 'Mapas (Temas)'},
        ),
        migrations.AlterModelOptions(
            name='mapasdetalle',
            options={'verbose_name_plural': 'Mapas Detalle'},
        ),
        migrations.RemoveField(
            model_name='mapas',
            name='titulo',
        ),
        migrations.AddField(
            model_name='mapas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapas',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapas',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, help_text='Descripión', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapas',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AddField(
            model_name='mapas',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mapas',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mapas',
            name='tema',
            field=models.CharField(default=1, help_text='Título del tema de mapas', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapas',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/mapas', verbose_name='Imagen tema mapa (450x370 px)'),
        ),
    ]
