# Generated by Django 3.2.19 on 2024-08-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0031_auto_20240808_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapas',
            options={'verbose_name_plural': 'Mapas (Temas)'},
        ),
    ]
