# Generated by Django 3.2.19 on 2024-08-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0032_alter_mapas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapas1',
            options={'verbose_name_plural': 'Mapas Detalle'},
        ),
    ]
