# Generated by Django 3.2.19 on 2024-08-09 13:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0033_alter_mapas1_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapas',
            name='titulo',
        ),
        migrations.AddField(
            model_name='mapas',
            name='descripion',
            field=models.CharField(default=1, help_text='Descripión', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapas',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AddField(
            model_name='mapas',
            name='tema',
            field=models.CharField(default=django.utils.timezone.now, help_text='Título del tema de mapas', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapas',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/mapas', verbose_name='Imagen tema mapa (450x370 px)'),
        ),
    ]
