# Generated by Django 3.2.19 on 2024-08-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0034_auto_20240809_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapas',
            old_name='descripion',
            new_name='descripcion',
        ),
    ]
