# Generated by Django 3.2.19 on 2024-08-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0035_rename_descripion_mapas_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapas',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
