# Generated by Django 3.2.19 on 2024-08-10 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generales', '0036_mapas_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mapas1',
            new_name='MapasDetalle',
        ),
    ]
