from django.db import models


class ChiaDataset(models.Model):
    form_id = models.BigIntegerField(null=True, blank=True)
    v_fecha = models.DateTimeField(null=True, blank=True)

    nomb_censist = models.CharField(max_length=150, null=True, blank=True)
    apell_censist = models.CharField(max_length=150, null=True, blank=True)
    cc_encuest = models.BigIntegerField(null=True, blank=True)
    telef_censist = models.CharField(max_length=50, null=True, blank=True)
    vigencia = models.IntegerField(null=True, blank=True)

    dpto_cnmbr = models.CharField(max_length=200, null=True, blank=True)
    mpio_cnmbr = models.CharField(max_length=200, null=True, blank=True)
    vered_cnmbr = models.CharField(max_length=200, null=True, blank=True)
    pueblo_cnmbr = models.CharField(max_length=200, null=True, blank=True)
    resguard_cnmbr = models.CharField(max_length=200, null=True, blank=True)
    comunid_cnmbr = models.CharField(max_length=200, null=True, blank=True)

    dpto_ccdgo = models.CharField(max_length=50, null=True, blank=True)
    mpio_ccdgo = models.CharField(max_length=50, null=True, blank=True)
    vered_ccdgo = models.CharField(max_length=50, null=True, blank=True)
    pueblo_ccdgo = models.CharField(max_length=50, null=True, blank=True)
    resguard_ccdgo = models.CharField(max_length=50, null=True, blank=True)
    comunid_ccdgo = models.CharField(max_length=50, null=True, blank=True)

    acto_admin = models.CharField(max_length=200, null=True, blank=True)
    num_regis = models.CharField(max_length=100, null=True, blank=True)
    fecha_admin = models.DateField(null=True, blank=True)

    sector_cnmbr = models.CharField(max_length=200, null=True, blank=True)

    coord_x = models.FloatField(null=True, blank=True)
    coord_y = models.FloatField(null=True, blank=True)
    dir_viviend = models.CharField(max_length=300, null=True, blank=True)
    telef_vivien = models.CharField(max_length=50, null=True, blank=True)
    num_vivien = models.CharField(max_length=50, null=True, blank=True)

    ord_familia = models.CharField(max_length=50, null=True, blank=True)
    cant_integran = models.IntegerField(null=True, blank=True)
    intregante = models.CharField(max_length=200, null=True, blank=True)

    primer_nombre = models.CharField(max_length=200, null=True, blank=True)
    segun_nombre = models.CharField(max_length=200, null=True, blank=True)
    primer_apellido = models.CharField(max_length=200, null=True, blank=True)
    segun_apellido = models.CharField(max_length=200, null=True, blank=True)
    auto_ident = models.CharField(max_length=100, null=True, blank=True)
    pb_indig_pert = models.CharField(max_length=100, null=True, blank=True)
    auto_iden_filia = models.CharField(max_length=100, null=True, blank=True)
    parentesco = models.CharField(max_length=100, null=True, blank=True)
    nacionali = models.CharField(max_length=100, null=True, blank=True)
    tipo_ident = models.CharField(max_length=50, null=True, blank=True)
    num_doc = models.CharField(max_length=50, null=True, blank=True)
    sexo = models.CharField(max_length=20, null=True, blank=True)
    fech_naci = models.DateField(null=True, blank=True)
    edad = models.IntegerField(null=True, blank=True)

    lug_naci = models.CharField(max_length=200, null=True, blank=True)
    lug_naci_dpto = models.CharField(max_length=100, null=True, blank=True)
    lug_naci_mpio = models.CharField(max_length=100, null=True, blank=True)
    lug_naci_cual = models.CharField(max_length=200, null=True, blank=True)

    resdiden = models.CharField(max_length=200, null=True, blank=True)
    resid_dpto = models.CharField(max_length=100, null=True, blank=True)
    resid_mpio = models.CharField(max_length=100, null=True, blank=True)
    resid_otro = models.CharField(max_length=200, null=True, blank=True)

    nivel_escol = models.CharField(max_length=150, null=True, blank=True)
    estado_civil = models.CharField(max_length=80, null=True, blank=True)
    ocupacion = models.CharField(max_length=200, null=True, blank=True)

    hijos_vivo = models.IntegerField(null=True, blank=True)
    hijos_sobrevi = models.IntegerField(null=True, blank=True)
    fech_ult_hij = models.DateField(null=True, blank=True)

    fuera_resguar = models.CharField(max_length=10, null=True, blank=True)
    fuera_resguar_nombre_apellido_1 = models.CharField(max_length=200, null=True, blank=True)
    fuera_resguar_cedula_1 = models.CharField(max_length=50, null=True, blank=True)
    fuera_resguar_lugar_1 = models.CharField(max_length=200, null=True, blank=True)
    fuera_resguar_nombre_apellido_2 = models.CharField(max_length=200, null=True, blank=True)
    fuera_resguar_cedula_2 = models.CharField(max_length=50, null=True, blank=True)
    fuera_resguar_lugar_2 = models.CharField(max_length=200, null=True, blank=True)
    fuera_resguar_nombre_apellido_3 = models.CharField(max_length=200, null=True, blank=True)
    fuera_resguar_cedula_3 = models.CharField(max_length=50, null=True, blank=True)
    fuera_resguar_lugar_3 = models.CharField(max_length=200, null=True, blank=True)

    razon_migra = models.TextField(null=True, blank=True)

    altas = models.CharField(max_length=4, null=True, blank=True)
    altas_nombre_apellidos = models.CharField(max_length=300, null=True, blank=True)
    altas_identificacion = models.CharField(max_length=100, null=True, blank=True)

    fallecidos_12_meses = models.CharField(max_length=4, null=True, blank=True)
    fallecidos = models.IntegerField(null=True, blank=True)
    fallecidos_12_meses_nombre_apellidos = models.TextField(null=True, blank=True)
    fallecidos_12_meses_identificaion = models.CharField(max_length=100, null=True, blank=True)

    tenencia = models.CharField(max_length=200, null=True, blank=True)
    adjudicata = models.CharField(max_length=200, null=True, blank=True)
    uso_prncpl = models.CharField(max_length=200, null=True, blank=True)

    confl_pred = models.CharField(max_length=200, null=True, blank=True)
    tipo_confl = models.CharField(max_length=200, null=True, blank=True)
    dur_confl = models.CharField(max_length=100, null=True, blank=True)

    mej_viv = models.CharField(max_length=200, null=True, blank=True)
    mej_viv_otro = models.CharField(max_length=200, null=True, blank=True)
    resid_prac = models.CharField(max_length=200, null=True, blank=True)
    amenaz = models.CharField(max_length=200, null=True, blank=True)
    fuent_ingres = models.CharField(max_length=200, null=True, blank=True)
    ing_lab_mes = models.CharField(max_length=100, null=True, blank=True)
    sob_alim = models.CharField(max_length=50, null=True, blank=True)
    econo_prop = models.CharField(max_length=50, null=True, blank=True)
    econo_prop_cual = models.CharField(max_length=200, null=True, blank=True)

    gasto_mes = models.TextField(null=True, blank=True)
    valor_mensual_pensionmanutencion_76 = models.FloatField(null=True, blank=True)
    valor_mensual_transporte_escolar_77 = models.FloatField(null=True, blank=True)
    valor_mensual_internet_78 = models.FloatField(null=True, blank=True)
    valor_mensual_salud_79 = models.FloatField(null=True, blank=True)
    valor_mensual_recreacion_80 = models.FloatField(null=True, blank=True)
    valor_mensual_servicio_domestico_81 = models.FloatField(null=True, blank=True)
    valor_mensual_telefono_celular_82 = models.FloatField(null=True, blank=True)
    valor_mensual_gas_83 = models.FloatField(null=True, blank=True)
    valor_mensual_luz_84 = models.FloatField(null=True, blank=True)
    valor_mensual_agua_85 = models.FloatField(null=True, blank=True)
    valor_mensual_vestuario_86 = models.FloatField(null=True, blank=True)
    valor_mensual_alimentacion_87 = models.FloatField(null=True, blank=True)

    perc_deuda = models.CharField(max_length=50, null=True, blank=True)
    subs_hogar = models.CharField(max_length=50, null=True, blank=True)
    prog_ayud = models.CharField(max_length=200, null=True, blank=True)

    esp_edu = models.CharField(max_length=200, null=True, blank=True)
    esp_edu_prop = models.CharField(max_length=200, null=True, blank=True)
    sab_prop = models.CharField(max_length=200, null=True, blank=True)
    freq_asamb = models.CharField(max_length=100, null=True, blank=True)
    norm_resguard = models.CharField(max_length=100, null=True, blank=True)

    Resp_resgud = models.CharField(max_length=200, null=True, blank=True)
    resp_resgud_porque_no = models.CharField(max_length=300, null=True, blank=True)
    recon_aut = models.CharField(max_length=100, null=True, blank=True)

    sis_salud = models.CharField(max_length=100, null=True, blank=True)
    lug_salud = models.CharField(max_length=200, null=True, blank=True)
    mej_salud = models.CharField(max_length=200, null=True, blank=True)
    probl_salud = models.CharField(max_length=200, null=True, blank=True)
    probl_salud_cuales = models.TextField(null=True, blank=True)
    fort_salud = models.TextField(null=True, blank=True)
    bien_mental = models.CharField(max_length=200, null=True, blank=True)
    rol_guard = models.CharField(max_length=200, null=True, blank=True)
    rol_guard_cual_role = models.CharField(max_length=200, null=True, blank=True)
    seg_terri = models.CharField(max_length=100, null=True, blank=True)
    casos_inseg = models.CharField(max_length=200, null=True, blank=True)
    casos_inseg_cual_hecho = models.TextField(null=True, blank=True)
    alt_comuni = models.TextField(null=True, blank=True)
    tipo_resp = models.CharField(max_length=100, null=True, blank=True)
    resguardo = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.form_id) if self.form_id else str(self.id)
