# Generated by Django 5.1.3 on 2025-12-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiadataset',
            name='altas',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
