# Generated by Django 5.1.3 on 2025-12-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_chiadataset_altas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiadataset',
            name='fallecidos_12_meses',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='chiadataset',
            name='gasto_mes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chiadataset',
            name='ing_lab_mes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
