# Generated by Django 5.1.3 on 2025-12-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_chiadataset_fallecidos_12_meses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiadataset',
            name='pueblo_ccdgo',
            field=models.BigIntegerField(blank=True, max_length=50, null=True),
        ),
    ]
